// Food reducer
export const SET_FOOD = `SET_FOOD`;
export const SET_FOOD_FAILED = `SET_FOOD_FAILED`;
export const START_FOOD_FETCH = `START_FOOD_FETCH`;

// Promotion reducer
export const SET_PROMOTIONS = `SET_PROMOTIONS`;
export const SET_PROMOTIONS_FAILED = `SET_PROMOTIONS_FAILED`;
export const START_PROMOTIONS_FETCH = `START_PROMOTIONS_FETCH`;

// Order reducer
export const SET_ORDERS = `SET_ORDERS`;
export const START_ORDERS_FETCH = `START_ORDERS_FETCH`;
export const SUCCESS_ORDERS_FETCH = `SUCCESS_ORDERS_FETCH`;
export const FAILED_ORDERS_FETCH = `FAILED_ORDERS_FETCH`;

// cart reducer
export const ADD_ITEM_TO_CART = `ADD_ITEM_TO_CART`;
export const REMOVE_ITEM_FROM_CART = `REMOVE_ITEM_FROM_CART`;
export const DELETE_ITEM_FROM_CART = `DELETE_ITEM_FROM_CART`;
export const CLEAR_CART = `CLEAR_CART`;

// auth user
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// order reducer
export const FETCH_ORDERS = `FETCH_ORDERS`;
export const FETCH_ORDERS_START = `FETCH_ORDERS_START`;
export const FETCH_ORDERS_FAIL = `FETCH_ORDERS_FAIL`;
export const FETCH_ORDERS_SUCCESS = `FETCH_ORDERS_SUCCESS`;
export const PURCHASE_ORDER = `PURCHASE_ORDER`;
export const PURCHASE_ORDER_START = `PURCHASE_ORDER_START`;
export const PURCHASE_ORDER_FAIL = `PURCHASE_ORDER_FAIL`;
export const PURCHASE_ORDER_SUCCESS = `PURCHASE_ORDER_SUCCESS`;