// Food reducer
export const SET_FOOD = `SET_FOOD`;
export const SET_FOOD_FAILED = `SET_FOOD_FAILED`;
export const START_FOOD_FETCH = `START_FOOD_FETCH`;

// Promotion reducer
export const SET_PROMOTIONS = `SET_PROMOTIONS`;
export const SET_PROMOTIONS_FAILED = `SET_PROMOTIONS_FAILED`;
export const START_PROMOTIONS_FETCH = `START_PROMOTIONS_FETCH`;

// Order reducer
export const SET_ORDERS = `SET_ORDERS`;
export const START_ORDERS_FETCH = `START_ORDERS_FETCH`;
export const SUCCESS_ORDERS_FETCH = `SUCCESS_ORDERS_FETCH`;
export const FAILED_ORDERS_FETCH = `FAILED_ORDERS_FETCH`;

// cart reducer
export const ADD_ITEM_TO_CART = `ADD_ITEM_TO_CART`;
export const REMOVE_ITEM_FROM_CART = `REMOVE_ITEM_FROM_CART`;
export const DELETE_ITEM_FROM_CART = `DELETE_ITEM_FROM_CART`;
export const CLEAR_CART = `CLEAR_CART`;